export {
  config,
  getCredits,
  getMovieBundle,
  getMovieGenres,
  getMoviesByGenre,
  getMediaDetails,
  getPopularMovies,
  getSimilar,
  getTopRatedMovies,
  getTrending,
  getTrendingSeries,
  getPopularSeries,
  getTopRatedSeries,
  getSeriesByGenre,
  getTrailerKey,
  getRecommendations,
  getTvSeasonEpisodes,
  getVideos,
  imageFromPath,
  searchMedia
} from "./tmdb";
